version: '3.4'

services:
  course-catalog:
    image: course-catalog
    container_name: course-catalog
    ports: 
      - 80:80
    depends_on: 
      - node-api
  node-api:
    image: node-rest-api
    container_name: node-api
    ports: 
        - 5000:5000
    environment: 
        MONGO_DB_URL: mongodb://root:root@mongo:27017/olb?authSource=admin
    depends_on: 
        - mongo

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports: 
        - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
      image: mongo-express
      container_name: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: root